## Configuracion de Spring
spring:
  application:
    name: rp-ms-books-payments
  datasource:
    url: jdbc:mysql://localhost:3306/compras?useSSL=false&serverTimezone=UTC
    username: mi_usuario
    password: mi_contraseña
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

## Configuracion de Instancia 
server:
  port: 8020

## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: rp-ms-books-payments

#APIS
getLibro:
  url: http://rp-ms-books-catalogue